# Generated by Django 4.0.5 on 2022-11-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_telegramuser_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='notification_time',
        ),
    ]
