# Generated by Django 4.0.5 on 2022-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_telegramuser_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='notification_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
