version: '3'

services:
  web:
    build:
      context: .
      args:
        - DEV=true
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./HoraroBackend/media:/app/media/
      - .:/app/

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
       - staging_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A config.celery.app worker --beat --loglevel=debug
    volumes:
      - ./:/service
    links:
      - redis
    depends_on:
      - redis
      - db
    env_file:
      - .env

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A config.celery.app flower
    volumes:
      - ./:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  staging_postgres_data: