# Generated by Django 4.0.5 on 2022-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_blockuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
