name: Deploy-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 46.229.214.105
          username: prod
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
                  cd ~/prod_horaro/HoraroBackend/ &&\
                  git pull && cd .. && docker stop prod_horaro_web_1 &&\
                  docker-compose up -d --no-deps --build web && docker image prune -f
