name: Deploy

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "pytest"
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          debug: ${{ secrets.debug }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          EMAIL_HOST: = ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: = ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: = ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: = ${{ secrets.EMAIL_HOST_PASSWORD }}
