name: Deploy-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 46.229.214.105
          username: prod
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: cd ~ && echo "I'm here"
