name: Lint-test

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_DB: postgres
          envkey_POSTGRES_USER: postgres
          envkey_POSTGRES_PASSWORD: postgres
          envkey_POSTGRES_HOST: db
          envkey_POSTGRES_PORT: 5432
          envkey_POSTGRES_NAME: postgres
          envkey_SECRET_KEY: django-insecure-b(=r+o15ecqk0yslac@*^@w^5a
      - name: Lint
        run: docker-compose -f docker-compose.local.yml run --rm web sh -c "flake8 . --count --show-source --statistics --max-line-length 120"

      - name: Test
        run: docker-compose -f docker-compose.local.yml run --rm web sh -c "pytest"

